id: P38C5E544
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS68018
  title: ཞལ་གདམས་དང་མགུར་གླུ་གཅེས་བཏུས།
  volumes:
    76895aa516594c23a47ca0a5601f0bc5:
      image_group_id: I8LS68020
      title: ''
      base_file: v001.txt
  author: ''
